# Generated by Django 3.2 on 2022-09-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20220910_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(max_length=100, verbose_name='امتیاز'),
        ),
    ]
