# Generated by Django 3.2 on 2022-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.CharField(max_length=100, verbose_name='قیمت'),
        ),
    ]
