# Generated by Django 3.2 on 2022-09-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.IntegerField(verbose_name='زمان لازم'),
        ),
    ]
